version: '3'

services:
  tunnel:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    command: ngrok http -log stdout --authtoken $NGROK_AUTHTOKEN app:3000

  app:
    container_name: connect-example-app-node
    volumes:
      - .:/app
    build:
      context: .
    ports:
      - "3000:3000" # server port
      - "9229:9229" # debug port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 5s
      retries: 100

  installation:
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./app-install:/app
    build:
      context: .
      dockerfile: app-install/Dockerfile
    env_file:
      - .env
