version: '3'

services:
  tunnel:
    image: wernight/ngrok
    container_name: ngrok
    ports:
      - "4040:4040"
    command: ngrok http -log stdout --authtoken $NGROK_AUTHTOKEN app:3000

  app:
    container_name: app
    volumes:
      - .:/app
    build:
      context: .
    ports:
      - "3000:3000" # server port
      - "9229:9229" # debug port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthcheck"]
      interval: 10s
      retries: 5

  installation:
    container_name: install-to-jira
    depends_on:
      app:
        condition: service_healthy
    build:
      dockerfile: etc/app-install/Dockerfile
    env_file:
      - .env
