blank_issues_enabled: false
contact_links:
  - name: Atlassian Connect Documentation
    url: https://developer.atlassian.com/cloud/jira/platform/getting-started-with-connect/
    about: Get started with Atlassian Connect app framework

