# This is a basic workflow to help you get started with Actions

name: Push

on:
  # Only build on main branch when pushed (when PR is merged)
  push:
    branches:
      - main
  # Only build in PR on creation/update
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v4
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: |
          echo "krazziekay:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN_FOR_NPM_PACKAGES }}" >> .npmrc
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        uses: docker/build-push-action@v2.7.0
        with:
          file: Dockerfile

  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    concurrency: e2e
    steps:
      - uses: actions/checkout@v1
      - run: yarn install --frozen-lockfile
      - name: create .env file
        run: |
          echo "APP_URL=https://${{ secrets.NGROK_DOMAIN }}" > .env
          echo "NGROK_AUTHTOKEN=${{ secrets.NGROK_AUTHTOKEN }}" >> .env
          echo "NGROK_DOMAIN=${{ secrets.NGROK_DOMAIN }}" >> .env
          echo "ATLASSIAN_URL=${{ secrets.E2E_ATLASSIAN_URL }}" >> .env
          echo "JIRA_ADMIN_EMAIL=${{ secrets.E2E_JIRA_ADMIN_USERNAME }}" >> .env
          echo "JIRA_ADMIN_API_TOKEN=${{ secrets.E2E_JIRA_ADMIN_PASSWORD }}" >> .env
      - run: docker-compose up -d
      - run: yarn run test:e2e
